apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
spec:
  template:
    spec:
      containers:
      - name: counter
        image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}"
        command:
        - /bin/sh
        - -c
        - |
          for i in $(seq 1 10000); do
            echo $i
          done
      restartPolicy: Never
  backoffLimit: {{ .Values.job.backoffLimit }}
